### ISSUE TITLE
Compiled kernel package is huge

### ISSUE THREAD

**Issue by Strit** [matyas1995/linux-aarch64-rockpro64#2]
Hi.
The resulting package of the `makepkg` is over 150 MB's and over 700 MB installed.
That's over 2,5 times the size of the regular `linux-aarch64` kernel.

Why is that?

**Comment by matyas1995** [comment]
Basically I took the kernel config of Ayufan (I think I mixed it a bit with the default Arch kernel config), but it looks like it compiles against ALL ARMv8 boards that are configured in the kernel. That means, you will have a lot of installed DTBs for the different ARM boards. Also, it seems to compile all the default drivers of which you have got a lot since it compiles many drivers for PCIe devices.

You could squeeze the generated image by throwing out unneeded drivers and boards. I have not done that yet as I have not had the time. It is also not on top of my todo list, as the installation size does not say anything about RAM usage, as Linux only loads modules when they are needed.

I have tried to use the config of the linux-aarch64 kernel, but that does not have PCIe configured, which I need for my homeserver.

**Comment by matyas1995** [comment]
Of course, I also rather took a more loaded config as I have plenty of space on my SD card (the rootfs is on a HDD), so I did not care about unneeded drivers. If you have a config that is better suited for the RP64, I would very much like to see it.

**Comment by Strit** [comment]
Sadly I don't have such a config.

Would also be interested in one. :slightly_smiling_face:
